### PR TITLE
Merge full_driver branch back into master branch

### PR DESCRIPTION
**Pull request by jordanrh1**
This change adds presentation support to the render only driver.

### CODE REVIEW

**Comment by marekkedzierski** [comment]
Jordan, 

Are you sure that kernel.img is working? I've tried full driver install and after exchanging kernel.img device does not boot at all. Any ideas?

Thanks,

Marek

**Comment by jordanrh1** [comment]
Hi Marek, I'm investigating the issue. Which OS build are you running? Is it 10586?

**Comment by marekkedzierski** [comment]
Hi Jordan,my version:

Windows 10 Kernel Version 10586 MP (4 procs) Free ARM (NT) Thumb-2

After installing your kernel.img, I'm getting only colorful screen. 
I've found that you removed  devcon.exe update ros.inf ACPI\BCM2850 command from install instructions. Is that ok?

Thanks!

Marek

**Comment by marekkedzierski** [comment]
Jordan, 
I saw that you added new files and updated install instructions. Please let me know when you're done. 
I'll try to install full driver.

Thanks!

Marek

**Pull request merged**
